apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DATABASENAME
          value: admin
        - name: DATABASEUSER
          value: wordpress
        - name: DATABASEPASSWORD
          value: wordpress
        - name: DATABASEHOST
          value: mongodb://wordpress:wordpress@3.93.45.143:27017/admin

        name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            requests:
              memory: 0.25Gi
              cpu: 0.5
            limits:
              memory: 0.25Gi 
              cpu: 0.5

