# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: wordpressLoadbalancer
spec:
  selector:
    app: myjenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
